create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  date_of_birth date not null,
  gender text not null check (gender in ('male', 'female')),
  sexual_preference text check (sexual_preference in ('men', 'women', 'both')),
  relationship_status text check (relationship_status in ('single', 'separated', 'divorced', 'widowed')),
  has_children boolean,
  education text,
  occupation text,
  country_id integer references countries(id),
  city_id integer references cities(id),
  bio text,
  interests text,
  avatar_url text,
  whatsapp text,
  instagram text,
  facebook text,
  subscribed_email boolean not null default true,
  subscribed_phone boolean not null default false,
  subscribed_sms boolean not null default false,
  privacy_preferences jsonb default '{}',
  role text not null default 'member' check (role in ('member', 'host', 'host_plus', 'admin')),
  admin_comments text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
